name: pketh.org ＿φ(°-°=)
description: Please make it simple, radical and beautiful.
url: http://pketh.org
twitter:
  username: pketh
markdown: kramdown
highlighter: rouge
paginate: 4
paginate_path: "blog/page:num"
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
permalink: none

