name: pketh.org
description: Making things simple, radical and beautiful
url: http://pketh.org
twitter:
  username: pketh
markdown: kramdown
highlighter: rouge
paginate: 4
paginate_path: "blog/page:num"
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
permalink: none

